[package]
name = "aes_crypto"
version = "0.1.0"
edition = "2021"
license = "MIT"
description = "A platform-agnostic library for the AES cipher (Rijndael)"
repository = "https://github.com/sayantn/aes"

[features]
vaes = []

[dependencies]
cfg-if = "1"

[dev-dependencies]
hex = "0"
pretty_assertions = "1"
lazy_static = "1"