[target.mips-unknown-linux-gnu]
build-std = true

[target.mips-unknown-linux-musl]
build-std = true

[target.mips64-unknown-linux-gnuabi64]
build-std = true

[target.mips64-unknown-linux-muslabi64]
build-std = true

[target.mipsel-unknown-linux-gnu]
build-std = true

[target.mipsel-unknown-linux-musl]
build-std = true

[target.mips64el-unknown-linux-gnuabi64]
build-std = true

[target.mips64el-unknown-linux-muslabi64]
build-std = true