name: AArch64 Test
on:
  workflow_call:
    inputs:
      target:
        required: true
        type: string
      target-in-caps:
        required: true
        type: string

jobs:
  test-software:
    uses: ./.github/workflows/other.yml
    with:
      target: ${{ inputs.target }}

  test-neon:
    strategy:
      matrix:
        channel: [ stable, beta, nightly ]
    name: Test of Neon on ${{ inputs.target }} with ${{ matrix.channel }}
    uses: ./.github/workflows/runtest.yml
    with:
      target: ${{ inputs.target }}
      channel: ${{ matrix.channel }}
      env-vars: ${{ format('CARGO_TARGET_{0}_RUSTFLAGS=-C target-feature=+aes', inputs.target-in-caps) }}