name: common

on:
  push:
    branches:
      - master

jobs:
  style:
    name: Check Style
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          components: rustfmt
          profile: minimal
          override: true

      - name: Rustfmt check
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all --check

  test-x86:
    strategy:
      fail-fast: false
      matrix:
        target:
          # Tier 1
          - triple: x86_64-unknown-linux-gnu
            caps: X86_64_UNKNOWN_LINUX_GNU
          - triple: x86_64-pc-windows-gnu
            caps: X86_64_PC_WINDOWS_GNU
          - triple: x86_64-pc-windows-msvc
            caps: X86_64_PC_WINDOWS_MSVC
          - triple: x86_64-apple-darwin
            caps: X86_64_APPLE_DARWIN
          - triple: i686-unknown-linux-gnu
            caps: I686_UNKNOWN_LINUX_GNU
          - triple: i686-pc-windows-gnu
            caps: I686_PC_WINDOWS_GNU
          - triple: i686-pc-windows-msvc
            caps: I686_PC_WINDOWS_MSVC
          #Tier 2 with Host Tools
          - triple: x86_64-unknown-freebsd
            caps: X86_64_UNKNOWN_FREEBSD
          - triple: x86_64-unknown-illumos
            caps: X86_64_UNKNOWN_ILLUMOS
          - target: x86_64-unknown-linux-musl
            caps: X86_64_UNKNOWN_LINUX_MUSL
          - target: x86_64-unknown-netbsd
            caps: X86_64_UNKNOWN_NETBSD
    uses: ./.github/workflows/x86.yml
    with:
      target: ${{ matrix.target.triple }}
      target-in-caps: ${{ matrix.target.caps }}

  test-arm:
    strategy:
      fail-fast: false
      matrix:
        target:
          # Tier 1
          - triple: aarch64-unknown-linux-gnu
            caps: AARCH64_UNKNOWN_LINUX_GNU
          # Tier 2 with Host Tools
          - triple: aarch64-apple-darwin
            caps: AARCH64_APPLE_DARWIN
          - triple: aarch64-pc-windows-msvc
            caps: AARCH64_PC_WINDOWS_MSVC
          - triple: aarch64-unknown-linux-musl
            caps: AARCH64_UNKNOWN_LINUX_MUSL
    uses: ./.github/workflows/arm.yml
    with:
      target: ${{ matrix.target.triple }}
      target-in-caps: ${{ matrix.target.caps }}

  test-riscv:
    strategy:
      fail-fast: false
      matrix:
        target:
          # Tier 2 with Host Tools
          - triple: riscv64gc-unknown-linux-gnu
            caps: RISCV64GC_UNKNOWN_LINUX_GNU
    uses: ./.github/workflows/riscv.yml
    with:
      target: ${{ matrix.target.triple }}
      target-in-caps: ${{ matrix.target.caps }}

  test-other:
    strategy:
      fail-fast: false
      matrix:
        target:
          # Tier 2 with Host Tools
          - arm-unknown-linux-gnueabi
          - arm-unknown-linux-gnueabihf
          - armv7-unknown-linux-gnueabihf
          - loongarch64-unknown-linux-gnu
          - powerpc-unknown-linux-gnu
          - powerpc64-unknown-linux-gnu
          - powerpc64le-unknown-linux-gnu
          - s390x-unknown-linux-gnu
    uses: ./.github/workflows/other.yml
    with:
      target: ${{ matrix.target }}