name: X86 Test
on:
  workflow_call:
    inputs:
      target:
        required: true
        type: string

jobs:
  test-software:
    strategy:
      fail-fast: false
      matrix:
        channel: [ stable, beta, nightly ]
    name: Test of Software AES on ${{ inputs.target }} with ${{ matrix.channel }}
    uses: ./.github/workflows/runtest.yml
    with:
      target: ${{ inputs.target }}
      channel: ${{ matrix.channel }}