name: Run Test
on:
  workflow_call:
    inputs:
      target:
        required: true
        type: string
      channel:
        required: true
        type: string
      env-vars:
        required: false
        type: string
        default: ''

jobs:
  test:
    continue-on-error: ${{ inputs.channel == 'nightly' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - run: ${{ format('echo "{0}" >> $GITHUB_ENV', inputs.env-vars) }}

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ inputs.channel }}
          profile: minimal
          override: true

      - name: Build
        uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: build
          args: --target ${{ inputs.target }} ${{ inputs.channel == 'nightly' && '--features=nightly' || '' }}

      - name: Test
        uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: test
          args: --target ${{ inputs.target }} ${{ inputs.channel == 'nightly' && '--features=nightly' || '' }}

