name: Run Test
on:
  workflow_call:
    inputs:
      target:
        required: true
        type: string
      channel:
        required: true
        type: string
      target-features:
        required: false
        type: string
        default: ''
      extra-features:
        required: false
        type: string
        default: ''

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ inputs.channel }}
          default: true
          target: ${{ inputs.target }}
          components: clippy

      - run: echo "RUSTFLAGS=-C target-feature=${{ inputs.target-features }}" >> $GITHUB_ENV

      - name: Clippy
        run: cargo clippy --target ${{ inputs.target }} ${{ inputs.extra-features }} --no-deps -- -D clippy::pedantic

      - name: Test
        run: ci/run-docker.sh ${{ inputs.target }} ${{ inputs.extra-features }}

      - name: Doc
        run: cargo doc --target ${{ inputs.target }} ${{ inputs.extra-features }} --no-deps