name: Run Test
on:
  workflow_call:
    inputs:
      target:
        required: true
        type: string
      channel:
        required: true
        type: string
      env-vars:
        required: false
        type: string
        default: ''

jobs:
  test:
    continue-on-error: ${{ inputs.channel == 'nightly' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - run: sudo apt update && sudo apt upgrade -y
        continue-on-error: true

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ inputs.channel }}
          profile: minimal
          override: true
        if: inputs.channel != nightly

      # the nightly 2024-05-18 has a bug where it is not understanding -fuse-ld=lld
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly-2024-05-11
          profile: minimal
          override: true
        if: inputs.channel == 'nightly'

      - run: ${{ format('echo "{0}" >> $GITHUB_ENV', inputs.env-vars) }}

      - name: Build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --target ${{ inputs.target }} ${{ inputs.channel == 'nightly' && '--features=nightly' || '' }}

      # Install cross via cargo-binstall to save time
      - uses: cargo-bins/cargo-binstall@main
      - run: cargo binstall cross

      - name: Test
        uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: test
          args: --target ${{ inputs.target }} ${{ inputs.channel == 'nightly' && '--features=nightly' || '' }}