name: CI

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  style:
    name: Check Style
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - run: rustup update --no-self-update

      - name: Rustfmt Check
        run: cargo fmt --all --check

  test-aesni:
    strategy:
      matrix:
        channel: [ stable, beta, nightly ]
        target:
          - x86_64-unknown-linux-gnu
          # - i686-unknown-linux-gnu
    uses: ./.github/workflows/runtest.yml
    with:
      target: ${{ matrix.target }}
      channel: ${{ matrix.channel }}
      target-features: +sse4.1,+aes

  test-aesni-vaes:
    strategy:
      matrix:
        target:
          - x86_64-unknown-linux-gnu
          # - i686-unknown-linux-gnu
    uses: ./.github/workflows/runtest.yml
    with:
      target: ${{ matrix.target }}
      channel: nightly
      target-features: +vaes
      extra-features: --features=nightly

  test-aesni-vaes-avx512:
    strategy:
      matrix:
        target:
          - x86_64-unknown-linux-gnu
          # - i686-unknown-linux-gnu
    uses: ./.github/workflows/runtest.yml
    with:
      target: ${{ matrix.target }}
      channel: nightly
      target-features: +vaes,+avx512f
      extra-features: --features=nightly

  test-neon:
    strategy:
      matrix:
        channel: [ stable, beta, nightly ]
    uses: ./.github/workflows/runtest.yml
    with:
      target: aarch64-unknown-linux-gnu
      channel: ${{ matrix.channel }}
      target-features: +aes

  test-armv8:
    strategy:
      matrix:
        target:
          - armv7-unknown-linux-gnueabihf
          - armv7-unknown-linux-gnueabi
          - thumbv7neon-unknown-linux-gnueabihf
    uses: ./.github/workflows/runtest.yml
    with:
      target: armv7-unknown-linux-gnueabihf
      channel: nightly
      target-features: +v8,+aes
      extra-features: --features=nightly

  test-riscv64:
    uses: ./.github/workflows/runtest.yml
    with:
      target: riscv64gc-unknown-linux-gnu
      channel: nightly
      target-features: +zkne,+zknd
      extra-features: --features=nightly

  test-riscv32:
    uses: ./.github/workflows/runtest.yml
    with:
      target: riscv32gc-unknown-linux-gnu
      channel: nightly
      target-features: +zkne,+zknd
      extra-features: --features=nightly -Z build-std

  test-software:
    strategy:
      matrix:
        channel: [ stable, beta, nightly ]
        target:
          - x86_64-unknown-linux-gnu
          # - i686-unknown-linux-gnu
          - aarch64-unknown-linux-gnu
          - armv7-unknown-linux-gnueabi
          - armv7-unknown-linux-gnueabihf
          - thumbv7neon-unknown-linux-gnueabihf
          - riscv64gc-unknown-linux-gnu
          - powerpc-unknown-linux-gnu
          - powerpc64-unknown-linux-gnu
          - powerpc64le-unknown-linux-gnu
          - s390x-unknown-linux-gnu
          - i586-unknown-linux-gnu
          - sparc64-unknown-linux-gnu
        constant-time:
          - ''
          - --features=constant-time
    uses: ./.github/workflows/runtest.yml
    with:
      target: ${{ matrix.target }}
      channel: ${{ matrix.channel }}
      extra-features: ${{ matrix.constant-time }}

  test-software-build-std:
    strategy:
      matrix:
        target:
          - riscv32gc-unknown-linux-gnu
        constant-time:
          - ''
          - --features=constant-time
    uses: ./.github/workflows/runtest.yml
    with:
      target: ${{ matrix.target }}
      channel: nightly
      extra-features: ${{ matrix.constant-time }} -Z build-std