# This checks fmt, clippy, and does build and test on each arch for each impl using cross

name: Rust

on:
  workflow_call:
    inputs:
      target:
        required: true
        type: string
      target-in-caps:
        required: true
        type: string
      channel:
        required: true
        type: string

jobs:
  test-software-aes:
    name: Test of Software Impl on ${{ inputs.target }}
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/workflows/runtest.yml
        with:
          target: ${{ inputs.target }}
          channel: ${{ inputs.channel }}

  test-aesni:
    # simple test for x86(64)
    if: contains(inputs.target, '86')
    name: Test of AESNI on ${{ inputs.target }}
    uses: ./.github/workflows/runtest.yml
    with:
      target: ${{ inputs.target }}
      channel: ${{ inputs.channel }}
      target-feature: ${{ format('CROSS_TARGET_{0}_RUSTFLAGS=+sse4.1,+aes', inputs.target-in-caps) }}

  test-aesni-vaes:
    if: contains(inputs.target, '86') && inputs.channel == 'nightly'
    name: Test of AESNI with VAES on ${{ inputs.target }}
    uses: ./.github/workflows/runtest.yml
    with:
      target: ${{ inputs.target }}
      channel: nightly
      target-feature: ${{ format('CROSS_TARGET_{0}_RUSTFLAGS=+vaes', inputs.target-in-caps) }}

  test-aesni-vaes-avx512f:
    if: contains(inputs.target, '86') && inputs.channel == 'nightly'
    name: Test of AESNI with VAES and AVX-512 on ${{ inputs.target }}
    uses: ./.github/workflows/runtest.yml
    with:
      target: ${{ inputs.target }}
      channel: nightly
      target-feature: ${{ format('CROSS_TARGET_{0}_RUSTFLAGS=+vaes,+avx512f', inputs.target-in-caps) }}

  test-neon:
    if: startsWith(inputs.target, 'aarch64') || startsWith(inputs.target, 'arm64ec') || (startsWith(inputs.target, 'armv8') && inputs.channel == 'nightly')
    name: Test of Neon on ${{ inputs.target }}
    uses: ./.github/workflows/runtest.yml
    with:
      target: ${{ inputs.target }}
      channel: ${{ inputs.channel }}
      target-feature: ${{ format('CROSS_TARGET_{0}_RUSTFLAGS=+aes', inputs.target-in-caps) }}

  test-riscv:
    if: startsWith(inputs.target, 'riscv') && inputs.channel == 'nightly'
    name: Test of Neon on ${{ inputs.target }}
    uses: ./.github/workflows/runtest.yml
    with:
      target: ${{ inputs.target }}
      channel: nightly
      target-feature: ${{ format('CROSS_TARGET_{0}_RUSTFLAGS=+zkne,+zknd', inputs.target-in-caps) }}
