# This checks fmt, clippy, and does build and test on each arch for each impl using cross

name: Rust

on:
  workflow_call:
    inputs:
      target:
        required: true
        type: string
      target-in-caps:
        required: true
        type: string
      channel:
        required: true
        type: string

jobs:
  test-software-aes:
    runs-on: ubuntu-latest
    name: Test of Software Impl on ${{ inputs.target }}
    steps:
      - uses: actions/checkout@v3

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ inputs.channel }}
          target: ${{ inputs.target }}
          profile: minimal
          components: clippy
          override: true

      - name: Clippy
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: --target ${{ inputs.target }}

      - name: Build
        uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: build
          args: --target ${{ inputs.target }}

      - name: Test
        uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: test
          args: --target ${{ inputs.target }}

  test-aesni:
    # simple test for x86(64)
    if: contains(inputs.target, '86')
    runs-on: ubuntu-latest
    name: Test of AESNI on ${{ inputs.target }}
    steps:
      - uses: actions/checkout@v3

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ inputs.channel }}
          target: ${{ inputs.target }}
          profile: minimal
          components: clippy
          override: true

      - run: ${{ format('echo "CROSS_TARGET_{0}_RUSTFLAGS=+sse4.1,+aes"', inputs.target-in-caps) }}

      - name: Clippy
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: --target ${{ inputs.target }}

      - name: Build
        uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: build
          args: --target ${{ inputs.target }}

      - name: Test
        uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: test
          args: --target ${{ inputs.target }}

  test-aesni-vaes:
    if: contains(inputs.target, '86') && inputs.channel == 'nightly'
    runs-on: ubuntu-latest
    name: Test of AESNI with VAES on ${{ inputs.target }}
    steps:
      - uses: actions/checkout@v3

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ inputs.channel }}
          target: ${{ inputs.target }}
          profile: minimal
          components: clippy
          override: true

      - run: ${{ format('echo "CROSS_TARGET_{0}_RUSTFLAGS=+vaes"', inputs.target-in-caps) }}

      - name: Clippy
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: --target ${{ inputs.target }} --features=nightly

      - name: Build
        uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: build
          args: --target ${{ inputs.target }} --features=nightly

      - name: Test
        uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: test
          args: --target ${{ inputs.target }} --features=nightly

  test-aesni-vaes-avx512f:
    if: contains(inputs.target, '86') && inputs.channel == 'nightly'
    runs-on: ubuntu-latest
    name: Test of AESNI with VAES and AVX-512 on ${{ inputs.target }}
    steps:
      - uses: actions/checkout@v3

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ inputs.channel }}
          target: ${{ inputs.target }}
          profile: minimal
          components: clippy
          override: true

      - run: ${{ format('echo "CROSS_TARGET_{0}_RUSTFLAGS=+vaes,+avx512f"', inputs.target-in-caps) }}

      - name: Clippy
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: --target ${{ inputs.target }} --features=nightly

      - name: Build
        uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: build
          args: --target ${{ inputs.target }} --features=nightly

      - name: Test
        uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: test
          args: --target ${{ inputs.target }} --features=nightly
