name: X86 Test
on:
  workflow_call:
    inputs:
      target:
        required: true
        type: string
      target-in-caps:
        required: true
        type: string

jobs:
  test-software:
    strategy:
      fail-fast: false
      matrix:
        channel: [ stable, beta, nightly ]
    name: Test of Software AES on ${{ inputs.target }} with ${{ matrix.channel }}
    uses: ./.github/workflows/runtest.yml
    with:
      target: ${{ inputs.target }}
      channel: ${{ matrix.channel }}

  test-aesni:
    strategy:
      fail-fast: false
      matrix:
        channel: [ stable, beta, nightly ]
    name: Test of AESNI on ${{ inputs.target }} with ${{ matrix.channel }}
    uses: ./.github/workflows/runtest.yml
    with:
      target: ${{ inputs.target }}
      channel: ${{ matrix.channel }}
      env-vars: ${{ format('CROSS_TARGET_{0}_RUSTFLAGS=+sse4.1,+aes', inputs.target-in-caps) }}

  test-aesni-vaes:
    name: Test of AESNI with VAES on ${{ inputs.target }}
    uses: ./.github/workflows/runtest.yml
    with:
      target: ${{ inputs.target }}
      channel: nightly
      env-vars: ${{ format('CROSS_TARGET_{0}_RUSTFLAGS=+vaes', inputs.target-in-caps) }}

  test-aesni-vaes-avx512f:
    name: Test of AESNI with VAES and AVX-512 on ${{ inputs.target }}
    uses: ./.github/workflows/runtest.yml
    with:
      target: ${{ inputs.target }}
      channel: nightly
      env-vars: ${{ format('CROSS_TARGET_{0}_RUSTFLAGS=+vaes,+avx512f', inputs.target-in-caps) }}