name: X86 Test
on:
  workflow_call:
    inputs:
      target:
        required: true
        type: string
      target-in-caps:
        required: true
        type: string

jobs:
  test-software:
    uses: ./.github/workflows/other.yml
    with:
      target: ${{ inputs.target }}

  test-aesni:
    strategy:
      matrix:
        channel: [ stable, beta, nightly ]
    name: Test of AESNI on ${{ inputs.target }} with ${{ matrix.channel }}
    uses: ./.github/workflows/runtest.yml
    with:
      target: ${{ inputs.target }}
      channel: ${{ matrix.channel }}
      env-vars: ${{ format('CARGO_TARGET_{0}_RUSTFLAGS=-C target-feature=+sse4.1,+aes', inputs.target-in-caps) }}

  test-aesni-vaes:
    name: Test of AESNI with VAES on ${{ inputs.target }}
    uses: ./.github/workflows/runtest.yml
    with:
      target: ${{ inputs.target }}
      channel: nightly
      env-vars: ${{ format('CARGO_TARGET_{0}_RUSTFLAGS=-C target-feature=+vaes', inputs.target-in-caps) }}

# vaes-avx512 implementation cannot be tested on qemu as qemu apparently doesn't support 512-bit vaes, please use a cloud server
# possible options are AWS 7i,7i-flex,7a instances, GCloud N4,C3,C3D,N2(with Ice Lake), Azure Dv5,Dsv5,Ddv5,Ddsv5,Dlsv5,Dldsv5Dasv6,Dadsv6,Dalsv6,Daldsv6 etc